# Generated by Django 2.1.3 on 2019-01-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='html_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
