# Generated by Django 2.1.3 on 2019-01-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='isCached',
            field=models.BooleanField(default=False),
        ),
    ]
